---
title: "LPSolveExample"
output: html_document
---

```{r setup, echo=TRUE}
# install.packages("lpSolve")
library("lpSolve")
```
  
  
```{r lpsolve, echo=TRUE}
# Set up problem: maximize
# x1 + 9 x2 + x3 subject to
# x1 + 2 x2 + 3 x3 <= 9
# 3 x1 + 2 x2 + 2 x3 <= 15

# First, we define our objective function. We pass in the coefficients as a vector to f.obj
f.obj <- c(1, 9, 1)

# Next, we define our constraints. We pass in a matrix of the coefficients to f.con
f.con <- matrix (c(1, 2, 3, 3, 2, 2), nrow=2, byrow=TRUE)

# Now we're telling it that the direction of the constraints is <=
f.dir <- c("<=", "<=")

# Lastly, we define the right hand side of the equations (the values that the constraints are tied to)
f.rhs <- c(9, 15)


# Now run.

result <- lp("max", f.obj, f.con, f.dir, f.rhs)


# This tells us the optimal value of the objective function
result$obj.val

# But it does not tell us by default what values of x give it that value! 
result$solution

# What if we want the sensitivities? 
result$sens.coef.from

result$sens.coef.to

result$duals



```

```{r}
#Identify objective function
#C = 6x + 2y
#Identify constraints
#10x + 5y <= 60 
#8x + 2y <= 40
#y <= 5

time_constraint <- function(x) 12 - 2*x
space_constraint <- function(x) 20 - 4*x
small_stick_constraint <- function(x) 5

x <- 0:10
xlims <- c(0, 6)
ylims <- c(0, 20)

#plot(x, time_constraint(x), type="l", xlim=xlims, ylim=ylims, ylab="Y (Small Sticks)", xlab="X (Big Sticks)")
#polygon(x=c(0, 0, 6), y=c(0, 12, 0), col="lightblue")
#lines(x, space_constraint(x))
#polygon(x=c(0, 0, 4), y=c(12, 20, 4), col="khaki")
#polygon(x=c(0, 0, 4, 5), y=c(0, 12, 4, 0), col="lightgreen")
#lines(x, rep(small_stick_constraint(x), times=11))
#polygon(x=c(0, 0, 3.5, 4, 5), y=c(0, 5, 5, 4, 0), col="darkgreen")
#polygon(x=c(4, 5, 6), y=c(4, 0, 0), col="darkcyan")
#polygon(x=c(3.5, 3.75, 4), y=c(5, 5, 4), col="goldenrod1")
#polygon(x=c(3.75, 4, 6, 6), y=c(5, 4, 0, 5), col="gray")

plot(0, 0, xlim=c(0,6), ylim=c(0,6), ylab="Y (Small Sticks)", xlab="X (Big Sticks)")
polygon(x=c(0, 0, 3.5, 4, 5), y=c(0, 5, 5, 4, 0), col="darkgreen")
points(0, 0, pch=19, col="black")
points(5, 0, pch=19, col="black")
points(4, 4, pch=19, col="red")

# First, we define our objective function. We pass in the coefficients as a vector to f.obj
f.obj <- c(6, 2)

# Next, we define our constraints. We pass in a matrix of the coefficients to f.con
f.con <- matrix (c(10, 5, 8, 2, 0, 1), nrow=3, byrow=TRUE)

# Now we're telling it that the direction of the constraints is <=
f.dir <- c("<=", "<=", "<=")

# Lastly, we define the right hand side of the equations (the values that the constraints are tied to)
f.rhs <- c(60, 40, 5)


# Now run.
result <- lp("max", f.obj, f.con, f.dir, f.rhs)
result$solution
```

```{r}
#Identify objective function
#C = 3x + 2y
#Identify constraints
#2x + y <= 6
#x + 2y <= 6

# Let's graph it! 
constraint_one <- function(x) 6 - 2*x
constraint_two <- function(x) 3 - 0.5*x
x <- 0:10
constraint_one_points <- constraint_one(x)
constraint_two_points <- constraint_two(x)
limits <- c(0, 6)

plot(0, 0, xlim=limits, ylim=limits, type="l")
lines(x, constraint_one_points)
lines(x, constraint_two_points)
polygon(x=c(0, 0, 3), y=c(0, 6, 0), col="lightblue")
polygon(x=c(0, 0, 6), y=c(0, 3, 0), col="khaki")
polygon(x=c(0, 0, 2, 3), y=c(0, 3, 2, 0), col="lightgreen")

# We start at the origin, the basic feasible solution
points(0, 0, pch=19, col="cyan")

# We pivot to the next feasible solution
points(3, 0, pch=19)

# We pivot to the optimal feasible solution
points(2, 2, pch=19, col="red")

# Define our objective function. We pass in the coefficients as a vector to f.obj
f.obj <- c(3, 2)

# Next, we define our constraints. We pass in a matrix of the coefficients to f.con
f.con <- matrix (c(2, 1, 1, 2), nrow=2, byrow=TRUE)

# Now we're telling it that the direction of the constraints is <=
f.dir <- c("<=", "<=")

# Lastly, we define the right hand side of the equations (the values that the constraints are tied to)
f.rhs <- c(6, 6)


# Now run.
result <- lp("max", f.obj, f.con, f.dir, f.rhs)
result
result$solution

```


